name: CD Workflow

on:
  workflow_run:
    workflows: ["CI-Pipeline"]  # CI 워크플로우 이름
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Application
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            echo "### Change directory to Sasimee-Back ###"
            cd /home/opc/Sasimee-Back
            
            echo "### Pull origin main from github ###"
            git pull origin main
            
            echo "### Pull new image from dockerhub ###"
            docker compose build backend

            echo "### Shutdown existing container ###"
            docker compose down

            echo "### turnon new container ###"
            docker compose up -d
